name: fcs-iac-scanner-pipeline

on: 
  push:
    branches: 
      - master
      - main

permissions:
  id-token: write
  contents: write
  security-events: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: gcp-infra

      - name: Terraform Init
        run: terraform init
        working-directory: gcp-infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: gcp-infra

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var "project=${{ secrets.GOOGLE_PROJECT }}" -lock=false
        working-directory: gcp-infra

  fcs-scan:
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create scan results directory
        run: mkdir scan-results
      
      - name: Run FCS IaC Scan
        id: fcs
        uses: crowdstrike/fcs-action@v1.0.6
        with:
          falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
          falcon_region: 'us-1'
          path: 'gcp-infra/main.tf'
          project_owners: ${{ secrets.USER_EMAIL }}
          severities: 'high,medium, low'
          fail_on: 'medium=1'
          upload_results: true
          report_formats: 'sarif'
          output_path: 'scan-results/'
          version: '0.39.0'
        env: 
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

      - name: Show scan results
        run: cat scan-results/*.sarif

      - name: Upload SARIF report to GitHub Code scanning
        uses: github/codeql-action/upload-sarif@v3
        if: steps.fcs.outputs.exit-code != 0
        with:
          sarif_file: ./scan-results
          category: crowdstrike-fcs-iac-scanner

  terraform-apply:
    needs: [terraform-plan, fcs-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init
        working-directory: gcp-infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply --auto-approve -var "project=${{ secrets.GOOGLE_PROJECT }}" -lock=false
        working-directory: gcp-infra